export default {
  LOGIN_ROUTE: "/login",
  LOGOUT_ROUTE: "/logout",
  UPDATE_PASSWORD: "/updatePassword/:id",
  USERS_ROUTE: "users",
  USER_ID_ROUTE: "user/:id",
  EDIT_USER_ID: "user/edit/:id",
  PRODUCTS_ROUTE: "products",
  PRODUCT_ID_ROUTE: "product/:id",
  EDIT_PRODUCT_ID: "product/edit/:id",
  TRANSACTIONS_ROUTE: "transactions",
  TRANSACTION_ID_ROUTE: "transaction/:id",
  EDIT_TRANSACTION_ID: "transaction/edit/:id",
  TESTS_ROUTE: "tests",
  TEST_ID_ROUTE: "test/:id",
  EDIT_TEST_ID: "test/edit/:id",
};
